export const PAGINATION = {
    ITEMS_PER_PAGE: 5,
    PROJECTS_PER_PAGE: 5,
    PROGRAM_GROUP_PROJECTS_PER_PAGE: 5,
    USER_PROJECTS_API_PAGE_LIMIT: 25,
    ADMIN_PROJECTS_API_PAGE_LIMIT: 25,
    PROJECT_FILES_API_PAGE_LIMIT: 25,
    USERS_PER_PAGE: 10,
} as const;
