// /app/layout.tsx
// This file sets up the root layout for your application.
// It fetches the session on the server and passes it to the client-side SessionProvider.

import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "./component/SessionProvider"; 
import { getServerSession } from "next-auth"; // FIX: Import getServerSession
import { authOptions } from "@/lib/auth"; // FIX: Import authOptions

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  //title: "Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ // FIX: Make the component async
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // FIX: Fetch the session on the server-side
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* FIX: Pass the session prop to the client-side SessionProvider */}
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}

